[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  PRISMA_CLI_BINARY_TARGETS = "rhel-openssl-3.0.x"
  PRISMA_GENERATE_SKIP_AUTOINSTALL = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = [
    "node_modules/.prisma/client/**",
    "node_modules/@prisma/engines/**",
    "prisma/schema.prisma"
  ]
